### ISSUE TITLE
salmon not found

### ISSUE THREAD

**Issue by DomeJoyce** [snandiDS/prokseq#2]
Hello, I have a problem with the docker container. 
Following the instruction, I installed it properly, but salmon is not recognized as you can see here:

```
(py36) sh-5.0# python scripts/pipeline-v2.8.py -s samples.bowtie.PEsample -p param.input.bowtie -n 12
File (param.input.bowtie) found.
File (samples.bowtie.PEsample) found.

Checking required tools or packages:

       samtools : Found
         salmon : Not found
         fastqc : Found
         bowtie : Found
        afterqc : Found
      readFasta : Found
              R : Found
        GnBdCov : Found
        FeatCnt : Found

Checking R packages:

DESeq2 : TRUE
ggplot2 : TRUE
edgeR : TRUE
NOISeq : TRUE
limma : TRUE
clusterProfiler : TRUE
apeglm : TRUE



SALMON:
        salmon IS NOT FOUND!


     
Done with package checks. Seems all the required packages are available."
```
How to fix it? If I run the test it finish without error, but still salmon is not detected.

Thank you so much,

best

**Comment by snandiDS** [comment]
Please check the parameter file. Perhaps you commented the package (salmon)
in param.xxxxx.yaml file. Specify the path to the salmon package in the
parameter file as:
PATH SALMON : /root/prokseq/depend/salmon-latest_linux_x86_64/bin

\S

**Comment by snandiDS** [comment]
Please use the latest version "https://github.com/snandiDS/prokseq-v2.0."
