### ISSUE TITLE
R not found within Conda environment

### ISSUE THREAD

**Issue by Eudaimorium** [snandiDS/prokseq#3]
Hello,

I have prokseq set up on a computing cluster using Conda. When running the test samples, specific R packages can be found (DESeq2, etc), but R cannot be found in the initial check for required tools or packages. R is loaded (which enables specific packages to be found) and installed in both Conda environments.

Is it possible to specify the R path under these conditions?

Thanks.

**Comment by snandiDS** [comment]
Hi,

The package looks for R in the following address '/usr/bin' and
'/usr/local/bin'. If you can run R from any of these paths, it should work.
In case you want all the dependencies in place, you can work with Docker.

I hope this helps.

**Comment by Eudaimorium** [comment]
Thank you for the reply!

My institution's computational cluster has also recommended using a container due to the complexities of the environment. Ordinarily they do not allow Docker containers to be run on the cluster, which is why I tried Conda first, but they've agreed to help set up an alternative. Thanks!
