### ISSUE TITLE
No py36 environment in singulairty container converted from docker

### ISSUE THREAD

**Issue by maojn** [snandiDS/prokseq#4]
Hi,

We do not allow docker container in our shared cluster due to security reason. So I have converted the docker image into a singularity container. But there is only the base env in the container. No py36 env.

This is the singularity def file:
BootStrap: docker
From: snandids/prokseq-v2.0:latest

After built the singularity container, I shelled into the container and run:
Singularity> source /etc/profile.d/conda.sh
Singularity> conda activate py36
Could not find conda environment: py36
You can list all discoverable environments with `conda info --envs`.

bash: 1: command not found

Then I tried:
Singularity> conda info --envs
# conda environments:
#
base                  *  /usr

There is no py36 environment.

Thank you for your help.

**Comment by snandiDS** [comment]
Please use the latest version "https://github.com/snandiDS/prokseq-v2.0."

**Comment by ponomarevsy** [comment]
I am having the same issue with Singularity (i.e., there is no py36 environment in the image). I've tried these two commands but neither of them had py36 environment in it:
```
singularity pull prokseq-2.1.sif docker://snandids/prokseq-v2.1:v1
singularity pull prokseq-2.0.sif docker://snandids/prokseq-v2.0:latest
```
Any suggestions? Thanks.
