### ISSUE TITLE
Issue not finding 'R', and string indices error

### ISSUE THREAD

**Issue by reiverjohn** [snandiDS/prokseq#6]
I've installed ProkSeq using the "conda" method as described.  Running "scripts/runCheck.py" finds all of the applications, except 'R'.  We are loading 'R' through a modules system, and the executable is on the PATH.  Can you advise how runCheck.py "looks" for 'R'?  I get the following:

Checking required tools or packages:

       samtools : Found
         salmon : Found
         fastqc : Found
         bowtie : Found
        afterqc : Found
      readFasta : Found
              R : Not found
        GnBdCov : Found
        FeatCnt : Found

Checking R packages:

DESeq2 : TRUE
ggplot2 : TRUE
edgeR : TRUE
NOISeq : TRUE
limma : TRUE
clusterProfiler : TRUE
apeglm : TRUE
RUVSeq : TRUE
RColorBrewer : TRUE

In addition, I'm having an additional issue running the "pipeline" script.  I get the following error:
**_TypeError: string indices must be integers_**

I made sure to adjust the parameter input file to contain the correct paths to all applications.  Any ideas?

**Comment by snandiDS** [comment]
>
> I've installed ProkSeq using the "conda" method as described. Running
> "scripts/runCheck.py" finds all of the applications, except 'R'. We are
> loading 'R' through a modules system, and the executable is on the PATH.
> Can you advise how runCheck.py "looks" for 'R'? I get the following:
>
Try starting R from the command prompt/Terminal using the command 'R'. I
doubt the package R is not on the PATH.

> In addition, I'm having an additional issue running the "pipeline" script.
> I get the following error:
>
> *TypeError: string indices must be integers*
>
> I made sure to adjust the parameter input file to contain the correct
> paths to all applications. Any ideas?
>
Maybe the parameters in the parameter file have some issues. If you can
provide a little bit more information we can guess the problem.

Thanks

**Comment by reiverjohn** [comment]
"R" runs just fine from the command line.  It is definitely on the PATH.  Also note that strangely, the Bioconductor packages are found successfully, but not the main R executable.

Below is my parameter file (I've manually checked all the paths).  Note I tried adding "PATH R" just to see if that would help R be located (it didn't):

#       Describe the Bowtie options below as:
#BOWTIE:
#   -I : 0
#   -X : 500
#   -k : 1
#   -p : 1
#
#       In case the package salmon is to be run, uncomment the 
#	following options. These are the default values.
#	These options will overwrite the BOWTIE parameters.
SALMON:
   SALMONINDEX:
      -k : 29
   SALMONQUANT:
      -l : A
      -p : 2
      --validateMappings : "TRUE"
#
#       Define the parameters for AfterQC. Example default parameters
#       are shown as bellow. All the default parameters are taken.
#       Modify the parameter and value in case of any changes. One can
#	add the other parameters with value.
#AFTERQC:  
#   -s : 35
#   -n : 5 
#   -p : 35
#   --debubble : "TRUE"
#   -a : 5
#
#       Define the Featurecounts options as bellow:
FEATURECOUNTS:
   a : oldAnnotationGFF.gtf #Define the Featurecounts input GTF file.
   o : Count #Define the Featurecounts output file name.
#
#       Specify a count file name
COUNTFILE : countFile.csv
#
#       geneBody coverage.r require a bed file. Specify the name of bed file as bellow:
geneBody_coverage:
   r : oldAnnotationGFF.bed
#
#       Specify if batch effect removal is required. FALSE if not required, else TRUE.
BATCH_EFFECT_REMOVE : "FALSE"
#
#Remove Unwanted Variation from RNA-Seq Data
#To run RUVSeq, uncomment the following two lines.
RUVSeq:
   nc : 100 #Integer - Top 100 genes as ranked by edgeR p-values.
            #Negative control genes to estimate the factors of unwanted variation.
   GeneListFile : "testFile.bgl" #In case one does not want Empirical control genes, and have a file.
#
#       Parameters for pathway analysis.
#       For pathway analysis, define the organism in three alphabets as bellow.
#       ypy = Yersinia pseudotuberculosis
#       User need to change the keg abbreviation of their genome which can be
#       found in https://www.genome.jp/kegg/catalog/org_list.html. Here ypy is
#       the Yersinia pseudotuberculosis YPIII
#	If PATHWAY analysis is not required comment out the PATHWAY section.
#PATHWAY:
#   cutoffPositive : 2.0  #logfold upper limit
#   cutoffNegative : -2.0 #logfold lower limit
#   Organism : ypy
#   # For Gene Ontology of the pathway analysis, define GO term and gene name file.
#   TERM2GENE : data/TERM2GENE.csv 
#   TERM2NAME : data/TERM2NAME.csv

PATH R : /cm/shared/apps/R/4.1.0/bin
#       Specify the path to samtools
PATH SAMTOOLS : /home/j/jbjohnston/testPrseq/depend/samtools/bin
#       Specify the root path. That means where the ProkSeq bundle is unpacked.
#       The location should have the following folders
#       1. depend - contains all the binaries of the external packages
#       2. scripts - contains all the modules required for ProkSeq, and pipeline-vx.x.sh
#       3. data - Contains Gene ontology files for pathway analysis.
PATH ROOT : /home/j/jbjohnston/testPrseq
#       If the above environment (depend, scripts, data) is true, the following
#       line maye uncommented.
#PATH DEFAULT : "TRUE"
#       Specify the path to geneBody_coverage
PATH geneBody_coverage : /home/j/jbjohnston/testPrseq/depend/RSeQC-2.6.2/scripts/
#       Specify the path to FEATURECOUNTS
PATH FEATURECOUNTS : /home/j/jbjohnston/testPrseq/depend/subread-1.4.6-p5-Linux-i386/bin/
#       Specify the path to fastqc
PATH FASTQC : /home/j/jbjohnston/testPrseq/depend/FastQC
#       Specify the path to bowtie
PATH BOWTIE : /home/j/jbjohnston/testPrseq/depend/bowtie2/bowtie2-2.3.5.1-linux-x86_64
#       Specify the path to salmon if salmon is required
#PATH SALMON : /home/snandi/firojPipeline/version_2.7/depend/salmon-latest_linux_x86_64/bin
#       Specify the path to pypy required for running afterqc
PATH PYPY : /home/j/jbjohnston/testPrseq/depend/pypy2.7-v7.2.0-linux64/bin
#       Specify the path to readfasta
PATH READFASTA : /home/j/jbjohnston/testPrseq/depend
#
#       End of file "param.input"
#

**Comment by snandiDS** [comment]
Ah, there is the issue.

The package looks R in "/usr/bin" or in "/usr/local/bin," and you have R in
"/cm/shared/apps/R/4.1.0/bin."
I think you can either create a symbolic link or install it in /usr/local/.
I'll go with the former option.

Good luck!

**Comment by snandiDS** [comment]
Please use the latest version "https://github.com/snandiDS/prokseq-v2.0."
